world:
- null
Messages:
  text:
  - '&7[&c系统&7] &6坩埚上面放铁制活板门并右键可打开垃圾桶'
  - '&7[&c系统&7] &6仰望星空并下蹲或按F键可打开服务器菜单'
  - '&7[&c系统&7] &6更多功能正在制作中'
  - '&7[&c系统&7] &6打怪可获得铜钱'
  - '&7[&c系统&7] &6海带右键海龟和幻翼可骑乘'
  - '&7[&c系统&7] &6腐肉可烧制成皮革'